### ISSUE TITLE
Update Guzzle

### ISSUE THREAD

**Issue by itaelle** [anorgan/onfleet-client#4]
Hello,

Thanks for that lib quite good.
Is it possible in any way to update the Guzzle dependency to ^6.2 and tag a version of the repos with it?

Thanks!!

**Comment by anorgan** [comment]
Done in https://github.com/anorgan/onfleet-client/commit/59b40cca2fb33343312dc84e09a10188f8175c8c#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780
Closing :)
