### ISSUE TITLE
Entity->update yields error "Call to undefined method GuzzleHttp\Psr7\Response::json()".

### ISSUE THREAD

**Issue by rjdean123** [anorgan/onfleet-client#6]
Entity update method should use your Response type rather than the Guzzle base response type to avoid response->json() method not found error with guzzle 6.0+.

`$response = $this->client->put($this->endpoint .'/'. $this->id, [
            'json' => $this->toArray()
        ]);`

to

`$response = Response::fromResponse($this->client->put($this->endpoint .'/'. $this->id, [
            'json' => $this->toArray()
        ]));`

**Comment by anorgan** [comment]
This is fixed already
